export interface IIssue {
	id: string;
	summary: string;
	days: number;
	type: string;
	resolutionDate: string;
	createdDate: string;
	url: string;
}

// Generated by https://quicktype.io

export interface IIssueList {
	key: string;
	url: string;
	title: string;
	status: string;
	priority: string;
	updated: string;
	created: string;
	assignee?: string;
}
